# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddi < Formula
  desc "Paddi from the command line"
  homepage "https://github.com/paddi-app/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_darwin_amd64.tar.gz"
      sha256 "618d954099a9950c4c3253f4b9ec4fb3cfe0d131b08a7abcc4a5c3012a5dbe54"

      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_darwin_arm64.tar.gz"
      sha256 "6076e27bc15178e69047f749b22486c1f5bf0d58701ed14a8a8b5c264b4f9f48"

      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_linux_amd64.tar.gz"
      sha256 "f00795b5017e125e9d190ebc9cceab5821ec647bc1adbb33b02611a00eee2560"
      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_linux_arm64.tar.gz"
      sha256 "96035e0cdd4b9e7b43ddd1773c2c51174dcf79bb8af4facf9c32a5fde22dfb76"
      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  test do
    system "#{bin}/paddi", "--version"
  end
end
