# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddi < Formula
  desc "Paddi from the command line"
  homepage "https://github.com/paddi-app/cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_darwin_amd64.tar.gz"
      sha256 "bcee6d0c62c521842d1022a86b7ba7963fd85ca8f69542dae505d46a93aebb98"

      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_darwin_arm64.tar.gz"
      sha256 "aac96f8f4596c91506bc41708c26bbf9aeb6c5220fbf9f1cbecd733a2ec0f570"

      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_linux_amd64.tar.gz"
      sha256 "cc305c508510cb16c5eb16e3ca810fc924abac360c9d2d8c19df3a87e04d4beb"
      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/cli/releases/download/v0.1.0/paddi_0.1.0_linux_arm64.tar.gz"
      sha256 "16db64f06387f43bc5467714ea127e421dd8abc525e5b51d8e856f164f07fc87"
      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  test do
    system "#{bin}/paddi", "--version"
  end
end
