# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paddi < Formula
  desc "Paddi from the command line"
  homepage "https://github.com/paddi-app/paddi"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/paddi-app/paddi/releases/download/v0.2.3/paddi_0.2.3_darwin_amd64.tar.gz"
      sha256 "e2e1b7a67d4447b4ba7fc78c75fe4a4907f7264df9ade6bd7c6aa878d8603a89"

      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/paddi-app/paddi/releases/download/v0.2.3/paddi_0.2.3_darwin_arm64.tar.gz"
      sha256 "e7483077ac5f81ff785ff1982a30f2fc781a6449c23c090b45672d2e3a6aba8c"

      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/paddi/releases/download/v0.2.3/paddi_0.2.3_linux_amd64.tar.gz"
      sha256 "50a42e13ad9c9f74d295e8d181faa84036293ef2a89f5cd297a75f2740b50919"
      define_method(:install) do
        bin.install "paddi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/paddi-app/paddi/releases/download/v0.2.3/paddi_0.2.3_linux_arm64.tar.gz"
      sha256 "e0c6252cb86393e87a769064f3706b7b90dee426fe6f90d35a5f964ac1adc6ac"
      define_method(:install) do
        bin.install "paddi"
      end
    end
  end

  test do
    system "#{bin}/paddi", "--version"
  end
end
